In [3]:
import cvxpy as cp
import numpy as np

In [57]:
#CHSH inequality (2 measurements with outputs 1,-1)
#Direct problem
H=np.array([[1,1],[1,-1]])
Z=np.zeros((2,2))
W=np.block([[Z,H],[H,Z]])
g01=cp.Variable()
g02=cp.Variable()
g03=cp.Variable()
g12=cp.Variable()
g13=cp.Variable()
g23=cp.Variable()
G=cp.bmat([[1,g01,g02,g03],
            [g01,1,g12,g13],
            [g02,g12,1,g23],
            [g03,g13,g23,1]])
dirprob=cp.Problem(cp.Maximize(1/2*cp.trace(W@G)),[G>>0])
dirprob.solve()
print("The optimal value of the direct problem is", dirprob.value)
print("A solution G is")
print(G.value)
print()
#Dual problem
lam1=cp.Variable()
lam2=cp.Variable()
lam3=cp.Variable()
lam4=cp.Variable()
L=cp.bmat(np.diag((lam1,lam2,lam3,lam4)))
C=cp.bmat(L+(-1/2)*W)
dualprob=cp.Problem(cp.Minimize(cp.trace(L)),[C>>0])
dualprob.solve()
print("The optimal value of the dual problem is", dualprob.value)
print("A solution L is")
print(L.value)
print()
print("The theoretical quantum bound is", 2*np.sqrt(2))

The optimal value of the direct problem is 2.8284271229966897
A solution G is
[[ 1.00000000e+00  8.04219755e-16  7.07106781e-01  7.07106781e-01]
 [ 8.04219755e-16  1.00000000e+00  7.07106781e-01 -7.07106781e-01]
 [ 7.07106781e-01  7.07106781e-01  1.00000000e+00 -1.15143033e-15]
 [ 7.07106781e-01 -7.07106781e-01 -1.15143033e-15  1.00000000e+00]]

The optimal value of the dual problem is 2.828427124616022
A solution L is
[[0.70710678 0.         0.         0.        ]
 [0.         0.70710678 0.         0.        ]
 [0.         0.         0.70710678 0.        ]
 [0.         0.         0.         0.70710678]]

The theoretical bound is 2.8284271247461903


In [63]:
#Chained CHSH inequalities for n measurements with outputs 1,-1
n=3
#Direct problem
Z=np.zeros((n,n))
B=np.copy(Z)
B[0][0]=1
B[n-1][0]=-1
for i in range(1,n):
    B[i-1][i]=1
    B[i][i]=1
W=np.block([[Z,B.T],[B,Z]])
G=cp.Variable((2*n,2*n), symmetric=True)
dirprob=cp.Problem(cp.Maximize(1/2*cp.trace(W@G)),[G>>0]+[G[i][i]==1 for i in range(2*n)])
dirprob.solve()
print("The optimal value of the direct problem is", dirprob.value)
print("A solution G is")
print(G.value)
print()
#Dual problem
lams=cp.Variable(2*n)
L=cp.diag(lams)
C=cp.bmat(L+(-1/2)*W)
dualprob=cp.Problem(cp.Minimize(cp.trace(L)),[C>>0])
dualprob.solve()
print("The optimal value of the dual problem is", dualprob.value)
print("A solution L is")
print(L.value)
print()
#Theoretical bound
bound=2*n*np.cos(np.pi/(2*n))
print("The theoretical quantum bound is", bound)

The optimal value of the direct problem is 5.196152427563775
A solution G is
[[ 1.00000000e+00  4.99999996e-01 -4.99999996e-01  8.66025405e-01
  -3.79572027e-16 -8.66025405e-01]
 [ 4.99999996e-01  1.00000000e+00  4.99999996e-01  8.66025405e-01
   8.66025405e-01  6.11311728e-15]
 [-4.99999996e-01  4.99999996e-01  1.00000000e+00  5.70550364e-15
   8.66025405e-01  8.66025405e-01]
 [ 8.66025405e-01  8.66025405e-01  5.70550364e-15  1.00000000e+00
   4.99999996e-01 -4.99999996e-01]
 [-3.79572027e-16  8.66025405e-01  8.66025405e-01  4.99999996e-01
   1.00000000e+00  4.99999996e-01]
 [-8.66025405e-01  6.11311728e-15  8.66025405e-01 -4.99999996e-01
   4.99999996e-01  1.00000000e+00]]

The optimal value of the dual problem is 5.196152856924317
A solution L is
[[0.86602548 0.         0.         0.         0.         0.        ]
 [0.         0.86602548 0.         0.         0.         0.        ]
 [0.         0.         0.86602548 0.         0.         0.        ]
 [0.         0.         0.       